//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWash.DataLayer.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceVacancyMaster
    {
        public int Id { get; set; }
        public string Time { get; set; }
        public Nullable<int> Vacancy { get; set; }
    }
}
